source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RefershTable_Example', :exclusive => true do
  pod "RefershTable", :path => "../"
end

target 'RefershTable_Tests', :exclusive => true do
  pod "RefershTable", :path => "../"

  
end
